
trigger: none
pr:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  Win10SDKVersion: 18362

steps:
- checkout: self
  clean: true
  lfs: false
  submodules: false
  persistCredentials: false

- task: PowerShell@2
  displayName: List Visual Studio Components
  inputs:
    targetType: filePath
    filePath: scripts/VSComponentList.ps1

- task: PowerShell@2
  inputs:
    targetType: filePath
    filePath: scripts/Install-WindowsSdkISO.ps1
    arguments: ${{ Win10SDKVersion }}
  displayName: 'Install Windows SDK (${{ Win10SDKVersion }})'

- task: CmdLine@2
  displayName: Install Haul dependencies
  inputs:
    script: yarn install --frozen-lockfile

- task: CmdLine@2
  displayName: Install RNW E2E Test App dependencies
  inputs:
    script: yarn install --frozen-lockfile
    workingDirectory: fixtures/react_native_windows_e2e_app

- task: CmdLine@2
  displayName: Create bundle
  inputs:
    script: yarn run build:bundle
    workingDirectory: fixtures/react_native_windows_e2e_app

- task: CmdLine@2
  displayName: run-windows
  inputs:
    script: yarn run start:app --logging
    workingDirectory: fixtures/react_native_windows_e2e_app

- task: PowerShell@2
  displayName: Wait for app to launch
  inputs:
    targetType: inline # filePath | inline
    script: |
      Start-Sleep -Seconds 10

- task: CmdLine@2
  displayName: Run tests
  inputs:
    script: yarn run test --forceExit
    workingDirectory: fixtures/react_native_windows_e2e_app
