comment: off

coverage:
  status:
    changes: true
    project:
      default:
        target: auto
        threshold: null
        base: auto
    patch:
      default:
        target: auto
        threshold: null
        base: auto
