version: 2.1

commands:
  run_node_tests:
    parameters:
      cache_prefix:
        type: string
        default: ""
    steps:
      - checkout
      - restore_cache:
          keys:
          - << parameters.cache_prefix >>-dependencies-{{ checksum "package.json" }}
          - << parameters.cache_prefix >>-dependencies
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: << parameters.cache_prefix >>-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn test -i

executors:
  node_8:
    working_directory: ~/haul
    docker:
      - image: circleci/node:8
  node_10:
    working_directory: ~/haul
    docker:
      - image: circleci/node:10
  node_latest:
    working_directory: ~/haul
    docker:
      - image: circleci/node:latest

jobs:
  test_node_8:
    executor: node_8
    steps:
      - run_node_tests:
          cache_prefix: "node_8"
  test_node_10:
    executor: node_10
    steps:
      - run_node_tests:
          cache_prefix: "node_10"
  test_node_latest:
    executor: node_latest
    steps:
      - run_node_tests:
          cache_prefix: "node_latest"

workflows:
  version: 2
  test:
    jobs:
      - test_node_8
      - test_node_10
      - test_node_latest
