version: 2.1

executors:
  node_10:
    working_directory: ~/haul_node_10
    docker:
      - image: circleci/node:10
  node_latest:
    working_directory: ~/haul_node_latest
    docker:
      - image: circleci/node:latest

jobs:
  setup_node_10:
    executor: node_10
    steps:
      - checkout
      - attach_workspace:
          at: ~/haul_node_10
      - restore_cache:
          keys:
          - node-10-dependencies-{{ checksum "package.json" }}
          - node-10-dependencies
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: node-10-dependencies-{{ checksum "package.json" }}
      # Clear old coverage output
      - run: rm -rf ./.coverage_output
      - run: rm -rf ./coverage
      - persist_to_workspace:
          root: .
          paths: .
  
  check_coverage:
    executor: node_10
    steps:
      - attach_workspace:
          at: ~/haul_node_10
      - run: yarn coverage:report
      - run: yarn coverage:check
      - store_artifacts:
          path: coverage
          destination: coverage

  lint_and_typecheck_node_10:
    executor: node_10
    steps:
      - attach_workspace:
          at: ~/haul_node_10
      - run: yarn lint
      - run: yarn typecheck

  unit_test_node_10:
    executor: node_10
    steps:
      - attach_workspace:
          at: ~/haul_node_10
      - run: yarn test -i --coverage packages # run only tests in packages
      - persist_to_workspace:
          root: .
          paths:
            - ./.coverage_output/*.json
  
  e2e_rn_0_59x:
    executor: node_10
    steps:
      - attach_workspace:
          at: ~/haul_node_10
      - run: yarn test -i e2e/react_native_0_59x
      - persist_to_workspace:
          root: .
          paths:
            - ./.coverage_output/*.json

  e2e_rn_0_60x:
    executor: node_10
    steps:
      - attach_workspace:
          at: ~/haul_node_10
      - run: yarn test -i e2e/react_native_0_60x/
      - persist_to_workspace:
          root: .
          paths:
            - ./.coverage_output/*.json

  e2e_rn_0_60x_ts:
    executor: node_10
    steps:
      - attach_workspace:
          at: ~/haul_node_10
      - run: yarn test -i e2e/react_native_0_60x_ts
      - persist_to_workspace:
          root: .
          paths:
            - ./.coverage_output/*.json

  e2e_rn_0_60x_multibundle:
    executor: node_10
    steps:
      - attach_workspace:
          at: ~/haul_node_10
      - run: yarn test -i e2e/react_native_0_60x_multibundle
      - persist_to_workspace:
          root: .
          paths:
            - ./.coverage_output/*.json

  e2e_rn_0_61x:
    executor: node_10
    steps:
      - attach_workspace:
          at: ~/haul_node_10
      - run: yarn test -i e2e/react_native_0_61x/
      - persist_to_workspace:
          root: .
          paths:
            - ./.coverage_output/*.json
  
  e2e_monorepo_multibundle:
    executor: node_10
    steps:
      - attach_workspace:
          at: ~/haul_node_10
      - run: yarn test -i e2e/monorepo_multibundle
      - persist_to_workspace:
          root: .
          paths:
            - ./.coverage_output/*.json
  
  e2e_react_native_windows_current:
    executor: node_10
    steps:
      - attach_workspace:
          at: ~/haul_node_10
      - run: yarn test -i e2e/react_native_windows_current
      - persist_to_workspace:
          root: .
          paths:
            - ./.coverage_output/*.json

  e2e_react_native_windows_vnext:
    executor: node_10
    steps:
      - attach_workspace:
          at: ~/haul_node_10
      - run: yarn test -i e2e/react_native_windows_vnext
      - persist_to_workspace:
          root: .
          paths:
            - ./.coverage_output/*.json

  setup_node_latest:
    executor: node_latest
    steps:
      - checkout
      - attach_workspace:
          at: ~/haul_node_latest
      - restore_cache:
          keys:
          - node-latest-dependencies-{{ checksum "package.json" }}
          - node-latest-dependencies
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: node-latest-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths: .

  lint_and_typecheck_node_latest:
    executor: node_latest
    steps:
      - attach_workspace:
          at: ~/haul_node_latest
      - run: yarn lint
      - run: yarn typecheck

  unit_test_node_latest:
    executor: node_latest
    steps:
      - attach_workspace:
          at: ~/haul_node_latest
      - run: yarn test -i --coverage packages # run only tests in packages


workflows:
  version: 2
  test:
    jobs:
      # Node 10 jobs
      - setup_node_10
      - lint_and_typecheck_node_10:
          requires:
            - setup_node_10
      - unit_test_node_10:
          requires:
            - setup_node_10
      - e2e_rn_0_59x:
          requires:
            - setup_node_10
      - e2e_rn_0_60x:
          requires:
            - setup_node_10
      - e2e_rn_0_60x_ts:
          requires:
            - setup_node_10
      - e2e_rn_0_60x_multibundle:
          requires:
            - setup_node_10
       e2e_rn_0_61x:
          requires:
            - setup_node_10
      - e2e_monorepo_multibundle:
          requires:
            - setup_node_10
      - e2e_react_native_windows_current:
          requires:
            - setup_node_10
      - e2e_react_native_windows_vnext:
          requires:
            - setup_node_10
      - check_coverage:
          requires:
            - lint_and_typecheck_node_10
            - unit_test_node_10
            - e2e_rn_0_59x
            - e2e_rn_0_60x
            - e2e_rn_0_60x_ts
            - e2e_rn_0_60x_multibundle
            - e2e_monorepo_multibundle
            - e2e_react_native_windows_current
            - e2e_react_native_windows_vnext
      
      # Node (latest) jobs
      - setup_node_latest
      - lint_and_typecheck_node_latest:
          requires:
            - setup_node_latest
      - unit_test_node_latest:
          requires:
            - setup_node_latest
